<?php
$z[0]=Array("field","",228,247);
$z[0][4]['name']="title";
$z[1]=Array("global","",248,274);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",315,344);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",384,442);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",693,728);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n      <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      ",1025,1229);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li><a href='~typelink~' class='select'>~typename~</a></li>";
$z[6]=Array("field","",1335,1364);
$z[6][4]['name']="typename";
$z[7]=Array("field","",1399,1428);
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n          <li><a href=\"[field:arcurl/]\">[field:title/]</a><i>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</i></li>\r\n         ",1772,1938);
$z[8][4]['pagesize']="6";
$z[9]=Array("pagelist","",2014,2067);
$z[9][4]['listitem']="index,end,pre,next,pageno";
$z[10]=Array("include","",2144,2181);
$z[10][4]['filename']="footer.htm";

?>